### ISSUE TITLE
race / crash at startup

### ISSUE THREAD

**Issue by nzjrs** [dddomodossola/remi#110]
there is some sort of race condition where idle() can be called before main(), or where multiple clients can cause the widget to be constructed in an improper state.

I have seen this on a few occasions. I think we need to protect access of client.root with a lock

**Comment by dddomodossola** [comment]
Do you have a traceback?

**Comment by nzjrs** [comment]
Many,  but they are not helpful.

I'm looking into it now. Its nothing to serious and I'll fix it.

**Comment by PURPORC** [comment]
I think I am getting this too.

An example debugging session paused in `WebSocketsHandler.on_message()`:

> `clients` 

`{('127.0.0.1', 52268): <__main__.MyApp object at 0x050517B0>}`

Just one instance of MyApp.

Looking at the callbacks in runtimeInstances:

> `[v.eventManager.listeners for v in runtimeInstances.values() if getattr(v, 'eventManager',None) and v.eventManager.listeners]`

`<type 'list'>: [{'onclick': {'instance': <__main__.LoginArea object at 0x056A47D0>, 'funcname': 'login'}}, {'onchange': {'instance': <__main__.MyApp object at 0x050517B0>, 'funcname': 'on_view_selection_change'}}, {'onclick': {'instance': <__main__.MyApp object at 0x0519F890>, 'funcname': 'on_search_button_pressed'}}, {'onclick': {'instance': <__main__.LoginArea object at 0x056A47D0>, 'funcname': 'logout'}}, {'onclick': {'instance': <__main__.MyApp object at 0x0519F890>, 'funcname': 'button_update_views_on_click'}}, {'onclick': {'instance': <__main__.LoginArea object at 0x0519FC90>, 'funcname': 'login'}}, {'onclick': {'instance': <__main__.MyApp object at 0x0519F890>, 'funcname': 'on_clear_button_pressed'}}, {'onchange': {'instance': <__main__.MyApp object at 0x0519F890>, 'funcname': 'on_view_selection_change'}}, {'onclick': {'instance': <__main__.MyApp object at 0x050517B0>, 'funcname': 'button_update_views_on_click'}}, {'onclick': {'instance': <__main__.MyApp object at 0x050517B0>, 'funcname': 'on_search_button_pressed'}}, {'onclick': {'instance': <__main__.MyApp object at 0x050517B0>, 'funcname': 'on_clear_button_pressed'}}, {'onclick': {'instance': <__main__.LoginArea object at 0x0519FC90>, 'funcname': 'logout'}}]`

Wow, there are widgets here with callback to another MyApp object which is knocking around somewhere.

The problem for my app comes when that MyApp at 0x0519F890 never has its `idle()` method called.

A workaround might be to add the MyApp to clients, but I think the key will be the same as the existing one. :frowning: 

Otherwise would I need to kill the MyApps that have the problem?

1. look for App objects in the `runtimeInstances` that don't appear in `clients`
2. delete eventManagers referencing those App objects
3. delete App from `clients` with matching `get_instance_key()` 
4. call `send_spontaneous_websocket_message()` on the App objects to do a document.location.reload()

But I really feel like there is some clever change that can avoid these loose ends entirely.

It's a fairly uncommon problem which seems dependent on network conditions, but at the moment it means I need to bounce the server to fix it for one user which I don't like to do because others are using it happily at the same time.  It's also a confusing to have the server just go away. It takes a bit for the users to work out that the server bounced and they need to hit refresh ... .

Sorry for the verbiage, I am still just understanding the edge of the issue.

Have a nice weekend! :sunglasses:

**Comment by dddomodossola** [comment]
@PURPORC Thank you so much for the information. I will debug it soon.

**Comment by nzjrs** [comment]
There is actually another way to cause another similar problem - stale
clients calling the instance with id's that no longer exist. I have a fix
for that I will push asap.

**Comment by dddomodossola** [comment]
@nzjrs You mentioned a solution already implemented. Since we merged recently your commits from your branch, can I consider this bug fixed?

**Comment by nzjrs** [comment]
yip it's fixed AFAICT

**Comment by dddomodossola** [comment]
Well, thank you!
