### ISSUE TITLE
Browser problem running the GUI

### ISSUE THREAD

**Issue by nikoluis** [dddomodossola/remi#123]
Hello all,

Before i mention the problem, i would like to say that i just started to learn Python. I'm a native .NET programmer, i create HMI solutions (called SCADA) which run on Windows PCs, but now i want to create a small HMI that will run on Raspberry Pi. It will read values from a device (temperature/wind speed etc) using Modbus and present them to a simple GUI that will be available remotely from a browser (PC or mobile). I started with the widgets example that presents all the supported widgets. But when i connect with the browser(ANY browser), occassionaly i see what is shown on the attached picture. The foreground of the GUI is turned to dark gray color  with a floating blue square (it turns round and round to itself), making the GUI unusable. I already searched in this area for a solution and I apologise if there is already one. 

![remi browser issue](https://cloud.githubusercontent.com/assets/20124024/16331907/c69534d4-39fb-11e6-9d66-13c04c73b5f3.png)

**Comment by nzjrs** [comment]
The animated square indicates the client is waiting for a websocket
connection to the server.

This is a new feature, so it still might have problems on some browsers.

Can you run the example with debug, paste the console output here, and also
include the browser javascript console log

Hello all,

Before i mention the problem, i would like to say that i just started to
learn Python. I'm a native .NET programmer, i create HMI solutions (called
SCADA) which run on Windows PCs, but now i want to create a small HMI that
will run on Raspberry Pi. It will read values from a device
(temperature/wind speed etc) using Modbus and present them to a simple GUI
that will be available remotely from a browser (PC or mobile). I started
with the widgets example that presents all the supported widgets. But when
i connect with the browser(ANY browser), occassionaly i see what is shown
on the attached picture. The foreground of the GUI is turned to dark gray
color with a floating blue square (it turns round and round to itself),
making the GUI unusable. I already searched in this area for a solution and
I apologise if there is already one.

[image: remi browser issue]
<https://cloud.githubusercontent.com/assets/20124024/16331907/c69534d4-39fb-11e6-9d66-13c04c73b5f3.png>

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/dddomodossola/remi/issues/123>, or mute the thread
<https://github.com/notifications/unsubscribe/AACjo6RDSMqXqbCLv6KSGync8hf35bKWks5qO5FfgaJpZM4I9jhq>
.

**Comment by nzjrs** [comment]
Also, does the square go away after one second? Or does it stay for ever.

Please include details of browser versions and operating systems
On 24 Jun 2016 10:12, "Nick Stamou" <notifications@github.com> wrote:

Hello all,

Before i mention the problem, i would like to say that i just started to
learn Python. I'm a native .NET programmer, i create HMI solutions (called
SCADA) which run on Windows PCs, but now i want to create a small HMI that
will run on Raspberry Pi. It will read values from a device
(temperature/wind speed etc) using Modbus and present them to a simple GUI
that will be available remotely from a browser (PC or mobile). I started
with the widgets example that presents all the supported widgets. But when
i connect with the browser(ANY browser), occassionaly i see what is shown
on the attached picture. The foreground of the GUI is turned to dark gray
color with a floating blue square (it turns round and round to itself),
making the GUI unusable. I already searched in this area for a solution and
I apologise if there is already one.

[image: remi browser issue]
<https://cloud.githubusercontent.com/assets/20124024/16331907/c69534d4-39fb-11e6-9d66-13c04c73b5f3.png>

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/dddomodossola/remi/issues/123>, or mute the thread
<https://github.com/notifications/unsubscribe/AACjo6RDSMqXqbCLv6KSGync8hf35bKWks5qO5FfgaJpZM4I9jhq>
.

**Comment by nikoluis** [comment]
Thanks for your fast reply. I'm at work now, i can't run anything on the console. How can i run the example with debug? I must say that i run everyhing with virtualenv, as suggested.

**Comment by nzjrs** [comment]
How are you running it currently if not from the console?

You can add debug=True to the start() call in the example __main__

**Comment by nikoluis** [comment]
I have my Pi at home and i have already started the application from a ssh console. I used mtux to run it, so i can disconnect from Pi and keep it running, before coming to work. I also have setup my router to forward the port 8081 to my Pi's IP. This blue icon is not showing all the time. Sometimes i refresh the page and it shows ok. If you want, you can connect to http://rygar.selfip.com:8081.

**Comment by nzjrs** [comment]
You need to open the websocket port in addition to the http port.

**Comment by nzjrs** [comment]
To explain a bit more - your router is probably not forwarding / opening
the websocket port to the pi. You need to configure it to do so. You might
also have to explicitly set this port in start(). I'm on mobile atm, but
you can find some closed issues discussing this topic.
On 24 Jun 2016 10:39, "John Stowers" <john.stowers@gmail.com> wrote:

You need to open the websocket port in addition to the http port.

**Comment by nikoluis** [comment]
You are right :-(. I didn't even think of that. I thought that the websockets are running only on the Pi and the client (browser) does not interfere with them. I will do this when i get back home. Thanks for your replies.

As i said, i just started learing Python and all these are new to me, so again i apologize.

**Comment by nzjrs** [comment]
No worries. I'll close this for now, but please reopen if you have another issue.

**Comment by dddomodossola** [comment]
@nikoluis as John correctly says the parameter to the start() call you have to define is **websocket_port**

so i.e.:
`start(address="0.0.0.0", port=8081, websocket_port=5700)`

**Comment by nikoluis** [comment]
Hello. I've got some feedback. First of all, i setup my router to forward ports 8081 and 57000 to my Pi.
Then i changed the start() to:

` start(MyApp, debug=True, address='0.0.0.0', port=8081, websocket_port=57000, start_browser=False)` 

...as suggested. Then i connected from a browser outside my house (i connected to a friendly PC with teamviewer) and i keep getting the same picture (the blue square). Then i checked the page source code on the browser. It contains the following code:

```
function openSocket(){
    try{
        ws = new WebSocket('ws://192.168.69.14:57000/');
        console.debug('opening websocket');
        ws.onopen = websocketOnOpen;
        ws.onmessage = websocketOnMessage;
        ws.onclose = websocketOnClose;
        ws.onerror = websocketOnError;
    }catch(ex){ws=false;alert('websocketnot supported or server unreachable');}
}
```
The address 192.168.69.14 is my PI's IP. That's why the websocket connection can not be established from an external network. Then i changed the host_name parameter. First I used the DYNDNS hostname i own, but i get the following error upon starting the example:


```
remi.server      INFO     Started websocket server 0.0.0.0:57000
remi.server      INFO     Started httpserver http://127.0.0.1:8081/
remi.server.ws   INFO     connection established: ('router_ip_address', 7505)
remi.server.ws   DEBUG    handle
remi.server.ws   DEBUG    handshake
remi.server.ws   INFO     handshake complete
remi.server.ws   DEBUG    send_message: ack... -> ('router_ip_address', 7505)
remi.server.ws   ERROR    error parsing websocket
Traceback (most recent call last):
  File "/tmp/remi-master/remi/local/lib/python2.7/site-packages/remi-0.1-py2.7.egg/remi/server.py", line 229, in on_message
    if self not in clients[k].websockets:
KeyError: 0

```
Then i used my router public IP in the host_name and it works from every browser from anywhere (inside/outside my router). Well, i noticed that using the GUI updates every connected browser, but i think this behavior can change. I'm not that far yet. :-)

So why using the IP as the host_name works but not with the domain name? Am i missing something?

**Comment by nzjrs** [comment]
For your specific network configuration you need to also pass host_name=
dyndns.thing.com

After you get this working it would be cool if you could submit a
documentation patch against the README so this is clearer for the next
person

**Comment by nikoluis** [comment]
Forget it! It works fine if host_name() is either IP or my.domain.com. 

I don't want to learn HTML. I intend to invest time on REMI, so i will do my best to report any strange issues i come up with. 

How i submit documentation patches?

**Comment by nzjrs** [comment]
I think if you try to edit the README on github then it offers to fork the
repository and then create a pull request

**Comment by nikoluis** [comment]
ok thanks
