### ISSUE TITLE
How to individually style TreeItem objects?

### ISSUE THREAD

**Issue by JackMordaunt** [dddomodossola/remi#177]
I have a `Tree` with 2 levels of `TreeItem`: 1. "category" 2. "item". A category contains a list of items.

When an Item is "active" (according to some state in my app) I want it to appear green.
Similarly when all items in a category are "active" I want the category TreeItem to also appear green.

As it stands I have an update function that updates the `style` dict:
```
itm = TreeItem(...)
if itm is open:
    itm.style.update({"background-color": "green"})
else:
    itm.style.update({"background-color": "white"})
```

The problem is that all the TreeItem's share the "TreeItem" css class, so when a leaf item is set to green as in the example, all of the items get set to green, not just the item in question.

How would you go about styling an individual element based on some state? Is there away to only apply css styles to a specific DOM element inline? Via ID? 
Cheers!

Update: setting `itm.attributes["style"] = "background-color:green"` seems to not have an effect on the markup when I inspect it.

**Comment by dddomodossola** [comment]
@JackMordaunt 
This ```itm.attributes["style"] = "background-color:green"```  doesn't work because you should not *override* the value of **style** key because it gets overwritten each refresh. The right method to setup a style value is ```mywidget.style['background-color'] = 'green'```.

However, you gets the descendants of an item inheriting the css parameter of the parents because they have no default property. You can solve in different ways:
- Define an additional css property in the *style.css* file for a specific TreeItem class. Using a css .class selector you can customize a particular style, setting it up on a widget by means of Tag.add_class(..) method.
- Setup each TreeItem instance by setting the standard color you expect to have ```treeitem.style['background-color'] = 'black'``` so it will not get automatically the inherited one. You can do this in a clean way making an overload of the TreeItem class.

Regards.

**Comment by JackMordaunt** [comment]
`Tag.add_class(..)` looks like what I need. Thanks!
