### ISSUE TITLE
A General Purpose Dialog

### ISSUE THREAD

**Issue by KenT2** [dddomodossola/remi#22]
I noticed that the INPUT DIALOG generates a new web page and returned to the previous one when OK was pressed. 

I just wondered if there could be a general purpose 'DIALOG'. It would have OK and Cancel buttons. It would be able to have any of the Widgets that the main gui page has (maybe with exceptions). The values of the widgets would be read by App when the OK button is pressed in the on_confirm event method using the read_value method for each of the widgets. The values would not be returned as a list as in the InputDialog.

**Comment by dddomodossola** [comment]
Hi Ken,

I built a GeneralDialog as you suggested. 
You can:
* add_field(fieldName, fieldWidget) : this function allows to add custom field to the dialog. The dialog is automatically resized (vertically) to contain the new widget;

* add_field_with_label(fieldName, fieldWidget) : this function allows to add custom field to the dialog, adding a label on the left. The dialog is automatically resized (vertically) to contain the new widget;

* get_field(fieldName): to get back the field after an on_confirm event. I can't implement a "get_value" function because the dialog can contain different kind of widgets.

Can we close this issue? ;-)

**Comment by KenT2** [comment]
Just checking that my app works with the latest gui before trying a GenericDialog. InputDialog and other dialogs which is based on GenericDialog have lost their on_cancel_value_listener methods (name has been changed from on_abort_cancel_listener)

**Comment by dddomodossola** [comment]
I forgot to inform you. For the GeneralDialog, I have changed the register functions to:
*set_on_cancel_dialog_listener
*set_on_confirm_dialog_listener

For the InputDialog and the FileSelectionDialog, we have the same functions as per the GeneralDialog, and also:
*set_on_confirm_value_listener

The names are changed, but the functionality is the same.

**Comment by KenT2** [comment]
I understand now about confirm and cancel. However I think it would be more understandable for beginners if sub-classes of Generic Dialog had their own cancel and confirm methods.

**Comment by KenT2** [comment]
I have tested the GenericDialog with text, label and dropdown fields. It works well except if two fields have the same label (fieldName), then one of the fields is not displayed because the label is being used as the key for a dictionary. Looks like fieldName is really the key, and could be renamed to this, and the add_field_with_label can have an additional label field.

generic_object.get_field(key).get_text() works for InputText but some other types of field do not have get_value() methods.

I wonder if get_text should be changed to get_value so it is the same for all fields.

**Comment by dddomodossola** [comment]
Now TextInput has get_value function to make it compliant to other widgets. You can now do generic_object.get_field(key).get_value().

GeneralDialog functions add_field and add_field_with_label now have the parameter key. For add_field_with_label it is an additional parameter.

>I understand now about confirm and cancel. However I think it would be more understandable for beginners if sub-classes of Generic Dialog had their own cancel and confirm methods.

This will be more clear with the documentation. It is not elegant to replicate the functions inherited by the superclass only for readability. ;-)

Please feedback the changes in order to close the issue.

**Comment by KenT2** [comment]
Works a treat now, thanks
