### ISSUE TITLE
Error when trying to run the editor

### ISSUE THREAD

**Issue by bashkan** [dddomodossola/remi#251]
Hi, 
When I try to run the editor I receive an AttributeError saying that 'module' object has no attribute  'Progress'
Have you ever had this issue? Do you have any suggestions?
I tried to manually import html_helper in command line, it gave me the same error.

P.S.: I am new to python, so I apologize if I am asking a stupid question.
Regards,
Koray

**Comment by dddomodossola** [comment]
Hello @bashkan ,
The problem is caused by the fact that you installed remi from pypi, and you downloaded the editor from the master branch. The remi version on master branch is updated with new features, in this case the new feature is the Progress widget.
You can fix the problem in two ways:
- download the older editor branch from here https://github.com/dddomodossola/remi/tree/v1.2.2 ;
- install the most updated remi version directly from GitHub master "branch pip install git+https://github.com/dddomodossola/remi.git" 

Have a good development

**Comment by dddomodossola** [comment]
On pypi you find the stable version, without the latest updates.
Here, on GitHub master branch you have an "unstable" but most updated version.
In order to install the most updated version (the one on github) run the following command:
    `pip install git+https://github.com/dddomodossola/remi.git`

**Comment by bashkan** [comment]
Hello,
Since "pip install git+https://github.com/dddomodossola/remi.git" required that I have git installed, I preferred to download the older editor and it worked perfectly.
You have been great help, thank you for your support and the wonderful software.
Best Regards,
Koray
