### ISSUE TITLE
Unable to edit example

### ISSUE THREAD

**Issue by bashkan** [dddomodossola/remi#254]
Hi,
I was trying to edit one of the examples to learn how things work, but I failed every time. Here is what I did:
I opened root_widget_change_app.py and wanted to add another label by inserting this line:
lbl_koray = gui.Label("Label from Koray.....", style={'font-size':'20px'})
But no matter where I insert it, the command line says unexpected indent. Can you please tell what I am doing wrong? One thing I noticed was, when I opened the example with notepad, it looks strange:
![notepad](https://user-images.githubusercontent.com/27769228/49374426-54dc5d00-f712-11e8-9a71-95b376f97ffd.png)
![the error](https://user-images.githubusercontent.com/27769228/49374432-5c9c0180-f712-11e8-9837-4cac5904b03d.png)

**Comment by dddomodossola** [comment]
@bashkan the problem seems to be you are using tabs instead of spaces in the code. Please use the same indentation character and all will be ok. maybe you are using a simple text editor like notepad++, consider to change the editor settings to use spaces instead of tabs, otherwise it will be difficult. you can also adopt a more advanced editor like VS Code and all will be fine.

**Comment by bashkan** [comment]
Hi Davide,
You are 100% right as always :) I used spaces instead of tabs and it worked perfectly. And yes I was using Notepad++ I will look into VS Code right now.
Thanks again for your help and the awesome library.
Best Regards.
