### ISSUE TITLE
[PySimpleGUI] How to change range of a Slider

### ISSUE THREAD

**Issue by MikeTheWatchGuy** [dddomodossola/remi#276]
Let's try conversing through Issues.  We will be able to close them very quickly.  I struggle to post code on Reddit and it's difficult to add images.
On to my question....
I am trying to change the range of a Slider I created.

This is how I created it in the first place:
```python 
                element.Widget = remi.gui.Slider(layout_orientation = remi.gui.Widget.LAYOUT_HORIZONTAL, default_value=element.DefaultValue, min=element.Range[0], max=element.Range[1],step=element.Resolution)
```

Here was my guess as to how to do it:
```python
            self.Widget.style['min'] = '{}'.format(range[0])
            self.Widget.style['max'] = '{}'.format(range[1])
```

**Comment by dddomodossola** [comment]
Hello @MikeTheWatchGuy ,
You are correct, reddit makes it a bit difficult to share code. However, in order to change min and max values you need to do:

```python
    self.widget.attributes['min'] = "0"
    self.widget.attributes['max'] = "120"
```

here is an example
[repl example](https://repl.it/@DavideRosa/sliderchangeminmax)

If you inspect the browser page you can see the html representation of a slider like this:
`<input class="range" id="140707876162024" style="margin:0px;width:200px;height:30px;position:static;order:-1" type="range" min="5" max="100" step="1" value="41" autocomplete="off" data-parent-widget="140707876160736">`
Elements like *type* *min* *max* *step* are all attributes of the widget, differently *margin* *width* *height* *position* are style properties. That said I can change the *height* by doing:

`mywidget.style['height']='10px'`

i can change an attribute by doing:

`mywidget.attributes['step']='10'`

**Comment by MikeTheWatchGuy** [comment]
AH!  ATTRIBUTES!

Thank you!

I'm learning, just slowly.

**Comment by dddomodossola** [comment]
you are welcome ;-)

**Comment by MikeTheWatchGuy** [comment]
Awesome!  This worked for me.  Thank you for the education too.

I don't yet understand any of the html stuff you're posting.  I know nothing about java, javascript, html, nor web programming.  I'm afraid I'm really ignorant of these.  Which is why I'm really thankful you're helping so much!
