### ISSUE TITLE
remi idle() behavior before first connect

### ISSUE THREAD

**Issue by johnneren** [dddomodossola/remi#336]
Hi David :)

I noticed that the idle() function in REMI is only called after the first connection from a web browser has been made.

So if I start my python application, which uses the idle thread to do stuff, it will only work after the first connect has happened.
After the first connect the idle will keep getting called after the browser is disconnected from remi.

My current work around is to have start_browser=True in remis start() call because I need the idle() to run from the beginning but I don't really need the browser to pop up.

Is there any way to change this behavior so the idle() is also called before the first connect or is this working as intended?

I also have a side question :) When can we expect a new release of remi?
I would very much like to have #329 and #326 in a official version.

**Comment by dddomodossola** [comment]
Hello @johnneren . There is no possibility to change the behaviour of idle, but you can find another workaround at this link https://www.reddit.com/r/RemiGUI/comments/b36vmt/how_to_go_ahead_and_start_up_remi_app_immediately/ .
The problem is that remi can work with one or multiple clients, and it would be inconsistent to call idle before to have a client. 
My preferred solution would be to have a thread that starts before remi server. In this thread I would perform operations that must be executed regardless of the connected clients. You could than share information between the App and the global thread.
I would like to do a new release of remi this week, I hope to find out some spare time ;-)
Have a good code development

**Comment by johnneren** [comment]
@dddomodossola 
Thanks David.
I got a a thread started and shared it with remi so now the idle() only handles GUI refresh stuff :)

Cheers

**Comment by dddomodossola** [comment]
@johnneren I released the latest remi version to pypi. ;-)

**Comment by johnneren** [comment]
@dddomodossola

Awesome, I'll update my requirements.

Thanks!
