### ISSUE TITLE
Constant remi.gui.Widget.LAYOUT_HORIZONTAL disappeared!

### ISSUE THREAD

**Issue by PySimpleGUI** [dddomodossola/remi#350]
My code is now crashing because I'm using the constant `remi.gui.Widget.LAYOUT_HORIZONTAL`.  It was in release 2019.9 but disappeared in 2019.11.

Should I not have been using it?

It didn't appear to be working anymore anyway as my sliders are all horizontal now.  I don't recall if I ever got them working vertically or not.

Please advise what I should use so that I can quickly update everyone so that their code doesn't crash when they pick up the newest Remi for PyPI.

**Comment by dddomodossola** [comment]
Excuse me for the problem caused by the remi update.Attached you will find the corrected version of PySimpleGUIWeb.The Widget.LAYOUT_VERTICAL and Widget.LAYOUT_HORIZONTAL constants are now part of the Container widget. So now I use Container.LAYOUT_VERTICAL and Container.LAYOUT_HORIZONTAL. This is because it was not consistent to inherit the Widget container by all the widgets, not all widgets can contain other widgetss. This means that there are containers and non containers.
I tested the fix by running PySimpleGUIWeb.py (the included test project). Please give it a try and let me know if it works also for you.

**Comment by PySimpleGUI** [comment]
Thank you for the help!

I've never been able to get a vertical slider to work.

Despite this code seemingly setting the orientation correctly, they always display horizontally

![image](https://user-images.githubusercontent.com/46163555/72366073-88383c00-36c7-11ea-8b00-77a1321baa8b.png)

```python
        [Slider((1, 100), default_value=80, key='_SLIDER_', visible=True, enable_events=False, orientation='v')],
        [Slider((1, 100), default_value=80, key='_SLIDER2_', visible=True, enable_events=False, orientation='h')],
```

which in turn converts into this Remi code:
```python
                orient = remi.gui.Container.LAYOUT_HORIZONTAL if element.Orientation.lower().startswith('h') else remi.gui.Container.LAYOUT_VERTICAL
                element.Widget = remi.gui.Slider(layout_orientation=orient, default_value=element.DefaultValue, min=element.Range[0], max=element.Range[1],step=element.Resolution)
```

I printed out orient and in the horizontal case == True, vertical == False.

**Comment by dddomodossola** [comment]
Hello Mike, 
That parameter is not meant to be the widget orientation. It instead defines how widgets are arranged inside a container. It should neither be accepted as parameter for the Slider, its my mistake.
Remi has no options to show vertical sliders. I know it could be feasible with CSS, but it is a trick and causes sizing problems.
