### ISSUE TITLE
Method to push alerts to screen and to communicate acknowledgement back

### ISSUE THREAD

**Issue by m-kareem** [dddomodossola/remi#410]
Hi @dddomodossola,

thanks once again for your amazing library and continues support.
I am looking for the best way to implement a method to push alerts to screen and to communicate acknowledgement back from the user in my GUI.
I would very much appreciate if you can suggest anything or provide a simple example code.

Thanks and stay safe,

**Comment by jeffreyscottgraham** [comment]
Me too

**Comment by m-kareem** [comment]
Hi Davide (@dddomodossola),
just a reminder in case this question has missed your attention.

Thanks and regards,

**Comment by dddomodossola** [comment]
@m-kareem @jeffreyscottgraham Unfortunately we cannot show onscreen notifications, since remi apps are limited to browser window. Of course there are javascript notification API, and remi implements a simple interface, an example here https://github.com/dddomodossola/remi/blob/master/examples/notification_app.py. But we are unable to show controls like buttons "Yes" "No"... So you can show notifications, but you cannot get back user interaction.
