### ISSUE TITLE
InputNumber?

### ISSUE THREAD

**Issue by awesomebytes** [dddomodossola/remi#49]
Would it be possible to have an input supporting only numbers?
I can write letters in the actual SpinBox :S.

Maybe able to choose between Integer and some decimal point representation?

**Comment by dddomodossola** [comment]
Hi awesomebytes, SpinBox should work fine on new browsers supporting HTML5.
On browsers where this does not work, you can eventually use a trick like this:
*myspinbox.attributes[myspinbox.EVENT_ONKEYPRESS] = 'return event.charCode >= 48 && event.charCode <= 57'*
I prefer to not include internally these tricks in the library in order to avoid dirty code...

**Comment by awesomebytes** [comment]
Tried it, works! thank you! :)

**Comment by awesomebytes** [comment]
I improved it with:

    'return event.charCode >= 48 && event.charCode <= 57 || event.charCode == 46 || event.charCode == 13'

Now it accepts "." for floating point and also hitting Enter to set the value.
