### ISSUE TITLE
Nicer CSS

### ISSUE THREAD

**Issue by nzjrs** [dddomodossola/remi#79]
Everyone is into material design these days, any chance for a flatter more modern CSS look inspired by material?

**Comment by cyberpro4** [comment]
I totally agree with you about a global project restyle and material design (Taking as reference [Google](https://www.google.com/design/spec/material-design/introduction.html)).

We can proceed in two ways:

### Use a third-party library (for example http://materializecss.com/)

Pros:
- Less work
- Robust design

Cons:
- Responsive
- A bit heavy for clients
- Some framework inputs needs to be redesigned

### Build a custom material css/js library:

Pros:
- Not responsive
- Tailored around project

Cons:
- More work
- Initially buggy
- Some framework inputs needs to be redesigned

> Normally, responsive, is a feature not something bad, but our project can't work on mobile conceptually (Or it should?) since objects placement are forced by code.

In either case, as you can see, we need to redesign some inputs because we can't use the classic <select> tag for an option menu: those items can't be customized by css and need some work client side (javascript) and server side obviously ( see [http://materializecss.com/dropdown.html](http://materializecss.com/dropdown.html)).

**Comment by cyberpro4** [comment]
[http://iamsurface.com/](http://iamsurface.com/) seems very light but lack in some features / components meanwhile material-design-lite is a good choice.
I'll do some tests with material-design-lite

**Comment by nzjrs** [comment]
Using https://github.com/dddomodossola/remi/commit/e50d51c8b0feea35a5faa82e40a540b714f2eb36
and https://github.com/dddomodossola/remi/commit/35ce4c07a28ab920267f49449853d7edc9fc7f1a

you should now be able to completely test new CSS without modifying the remi core

```python
class MyApp(App):
    App.__init__(self, css_header="<link href='/res/newstyle.css' rel='stylesheet' />\n",
                                 html_header="extra javascript things")
```

**Comment by nzjrs** [comment]
Any updates?

**Comment by cyberpro4** [comment]
Not yet... I haven't found the time I was expecting. Feel free to change the style by yourself: I don't want slow down the project.

**Comment by dddomodossola** [comment]
I'm teaching myself about material design. I will try to implement the new style.

**Comment by nzjrs** [comment]
@dddomodossola  I would suggest that the material design aspect of this is actually quite small. The difficulty is making sure we don't write imprefectly structured HTML that is difficult to style later on. For example

 * we either need to mark specific containers with different classes (imagine some containers being marked with 'Card' to use the material design phrasing or we need to really split the widget hierarchy more into containers and other widgets (as I already suggested)
 * we really need to think if writing hardcoded widget sizes is the wisest thing to do in every widget

**Comment by nzjrs** [comment]
Personally, I have tried a few times to make some small changes to make the style better, but to really embrace material design we need to think about the issues I raised above

**Comment by dddomodossola** [comment]
@nzjrs to which issues you refers? #81? If I understood what you said, you are proposing to creating different containers, each one for a specific use. But, you have a plan for sure :-D. Which kind of containers do you expect and on which features they are differentiated?

**Comment by nzjrs** [comment]
I think it would be more of an API separation, perhaps so you could have Vertical and Horizontal boxes that could float their children of wanted, or place them at fixed locations. There is also the question of implementing a tab/notebook container - how best to do that within REMI and in a manner compatible with material or other modern CSS frameworks.

**Comment by nzjrs** [comment]
And yeah, I basically am referring to #8, although I did some of the foundations for that in my recent commits. It is definately in progress.

**Comment by dddomodossola** [comment]
Ok, and so I will concentrate my work on other parts of the project. ;-) (When I will come back at home, now I'm abroad now)

**Comment by dddomodossola** [comment]
Just to have more info, when you say Containers you mean something like Layouts? For example you will implement something like FlowLayout HorizontalLayout GridLayout and so on?

**Comment by MisterY** [comment]
Just to chip in - this is one of the things that would be possible with view/controller separation. Anyone could implement a different styling library, according to preferences or organizational rules.
If Remi simply provides access to element properties and class/style dictionaries, it would already allow for modification of any UI element.
Otherwise, there will always be people who will need some other functionality and reimplementing HTML in Python would take many hours that could be used for improving the library, parsers, and the tools that would help speed up and ease the development in general.
Maybe I'm biased, but I find it **much** easier to come up with a nice-looking form with HTML and CSS, using any available framework (Bootstrap, Bulma, whatever), web fonts, etc. than tweaking Python code to achieve the same. Just a thought.
